environment:
  build_version: 5.0.0
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)-alpha{build}'
before_build:
 - cmd: c:\Projects\Grace\nuget\nuget.exe restore Source/Grace.sln
build:
  project: Grace.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
