environment:
  build_version: 4.0.3
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
- cmd: nuget restore Source/Grace.sln
build:
  project: Source/Grace.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
